### ISSUE TITLE
ayo

### ISSUE THREAD

**Issue by Itamar1337** [xixmen/ogu-tool#1]
ayo ogu spam bot?? were you the guy spamming a week ago? 🤣

**Comment by xixmen** [comment]
i released the tool to a few people last month i never cared to do any botting besides tests

**Comment by Itamar1337** [comment]
cool, you got any other ogu tools?

**Comment by xixmen** [comment]
i can make a free autobump

**Comment by Itamar1337** [comment]
mind adding me on discord? ex#1414 I have been trying to make one for a while but failed if you can help I would be glad thanks.
